version: '2'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=user_service
#  migrations:
#      image: rdccosmo/flywaydb
#      volumes:
#          - data:/var/sql
#      links:
#          - mysql
#      environment:
#          - DATABASE_NAME=dbname
#          - DATABASE_USER=test
#          - DATABASE_PASSWORD=test
#          - DATABASE_PORT=3306
#          - DATABASE_ENCODING=utf8
#          - DATABASE_DRIVER=mysql
#          - MIGRATIONS_PATH=/var/www/html/migrations/sql